# Generated by Django 5.1.5 on 2025-02-19 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='Cityinterested',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AddField(
            model_name='contact',
            name='FranchiseType',
            field=models.CharField(default='', max_length=90),
        ),
    ]
