# Generated by Django 5.1.5 on 2025-03-19 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_contact_cityinterested_contact_franchisetype'),
    ]

    operations = [
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('desription', models.CharField(max_length=2000)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('photo', models.ImageField(default='', upload_to='blog/')),
            ],
        ),
        migrations.CreateModel(
            name='bookappointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('lastname', models.CharField(max_length=70)),
                ('email', models.CharField(max_length=70)),
                ('phonenumber', models.CharField(max_length=70)),
                ('selectsalon', models.CharField(default='', max_length=90)),
                ('selectservice', models.CharField(default='', max_length=80)),
                ('appointmentdate', models.CharField(default='', max_length=80)),
            ],
        ),
    ]
