# Generated by Django 5.1.5 on 2025-03-27 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_bookappointment_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookappointment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='bookappointment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
