# Generated by Django 5.1.5 on 2025-03-27 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_previousappointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='previousappointment',
            name='booking_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
