# Generated by Django 5.1.5 on 2025-03-31 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_previousappointment_booking_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='previousappointment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='upcoming', max_length=10),
        ),
    ]
