# Generated by Django 5.1.5 on 2025-03-31 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_previousappointment_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookappointment',
            name='appointmentdate',
            field=models.DateField(default='none', max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='previousappointment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
