# Generated by Django 5.1.5 on 2025-03-31 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_alter_previousappointment_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookappointment',
            name='status',
            field=models.CharField(choices=[('upcoming', 'Upcoming'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='upcoming', max_length=20),
        ),
        migrations.DeleteModel(
            name='previousappointment',
        ),
    ]
