# Generated by Django 5.1.5 on 2025-04-02 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_bookappointment_status_delete_previousappointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookappointment',
            name='status',
            field=models.CharField(choices=[('upcoming', 'Upcoming'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('deleteappointment', 'deleteappointment')], default='upcoming', max_length=20),
        ),
    ]
