# Generated by Django 5.1.5 on 2025-04-03 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_alter_bookappointment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookappointment',
            name='cancelreason',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='bookappointment',
            name='status',
            field=models.CharField(choices=[('upcoming', 'Upcoming'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='upcoming', max_length=20),
        ),
    ]
